### ISSUE TITLE
Illegal Argument Exception

### ISSUE THREAD

**Issue by meganminnear18** [HIES/red-vs-blue-meganminnear18#1]
It throws an exception at the setPenColor in the draw method. If I comment out the statement the map will draw completely in black, but with the statement it fully draws Texas, Massachusetts and a few counties in Maryland and then stops.

**Comment by meganminnear18** [comment]
Never mind, it was an issue in Maryland with Baltimore's voting data referencing both a Baltimore county and a Baltimore city county, so I just deleted city from the 2nd county. Would I have to make a special case in the getGeoData Method for this specific instance if I wanted to code a solution?

**Comment by TheCurlyWaffle** [comment]
Yes, you'd have to decide to either handle the discrepancy in `ElectoralMap` or your voting data files. Welcome to the messy world of working with data. : )
